version: 0.1.1.{build}
image: Visual Studio 2013

clone_depth: 1

platform:
    - x64
    - Win32

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Win32" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %archi%

before_build:
  - nuget restore -PackagesDirectory .\packages

build:
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild NppEventExec.vcxproj /p:configuration="%configuration%" /p:platform="%platform%"
